The purpose of this project is to aggregate raw workout data that I've collected over the course of multiple years from 
multiple fitness prorams, and to analyze my progress, identify trends, and predict future progress

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Importing personal workout data from Excel 
# Data is not in an easy to aggregate format and the different programs have data collected in different formats

ppl = pd.read_csv("PPL.csv")
pbv2 = pd.read_csv("PowerbuildingV2.csv")
pbv3 = pd.read_csv("PowerbuildingV3.csv")
btox = pd.read_csv("BTOxPPL.csv")
pbv1_2023 = pd.read_csv("2023PowerbuildingV1.csv")
pbv2_2023 = pd.read_csv("2023PowerbuildingV2.csv")
pbv1_2023.head(20)

,Unnamed: 0,Workout,Squat,Overhead Press,RDL,T-Bar Row,Hammer Curl,Full body 1,Deadlift,Bench Press,...,Pendlay row,Shrug machine,Front raise,Skullcrushers.1,Pull-up,Dip,EZ bar curl,Machine Lateral Raise.2,Abs,Upper
0,Week 1,Full Body,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3/6/2023,1,"215 x 5, 185 x 8, 185 x 8","70 x 8, 70 x 8, 70 x 8","85 x 12, 80 x 12, 80 x 12","35 x 14, 35 x 10","25 x 22, 25 x 14",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3/7/2023,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180 x 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3/8/2023,Rest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3/9/2023,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,3/10/2023,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3/11/2023,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,3/12/2023,Rest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Week 2,Upper/Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3/13/2023,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,3/14/2023,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,3/15/2023,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,3/16/2023,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"135 x 18, 135 x 14","90 x 25, 90 x 21","22.5 x 10, 20 x 12",27.5 x 14,NaN,NaN,NaN,NaN,NaN,NaN
13,3/17/2023,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,3/18/2023,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"19, 16","70 x 13, 70 x 10, 70 x 8","40 x 18, 40 x 14",NaN,NaN
15,3/19/2023,Rest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Week 3,Full body,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,3/20/2023,1,"225 x 8, 235 x 6, 235 x 4","75 x 9, 75 x 8, 75 x 7","130 x 12, 130 x 11","90 x 18, 100 x 12, 100 x 13","25 x 18, 25 x 16, 25 x 15",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,3/21/2023,2,NaN,NaN,NaN,NaN,NaN,NaN,"315 x 2, 315 x 2, 315 x 2, 315 x 2","170 x 7, 165 x 8, 165 x 7",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,3/22/2023,Rest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Renaming first column in each program to "Date"
# Removing week label and null rows

programs = [ppl, pbv2, pbv3, btox, pbv1_2023, pbv2_2023]

for program in programs:
    program.rename(columns = {'Unnamed: 0':'Date'}, inplace = True)
    for index, row in program.iterrows():
        if "Week" in str(row["Date"]):
            program.drop(index, inplace=True)
    program.dropna(subset=["Date"], inplace=True)

In [4]:
pbv1_2023.head(15)

,Date,Workout,Squat,Overhead Press,RDL,T-Bar Row,Hammer Curl,Full body 1,Deadlift,Bench Press,...,Pendlay row,Shrug machine,Front raise,Skullcrushers.1,Pull-up,Dip,EZ bar curl,Machine Lateral Raise.2,Abs,Upper
1,3/6/2023,1,"215 x 5, 185 x 8, 185 x 8","70 x 8, 70 x 8, 70 x 8","85 x 12, 80 x 12, 80 x 12","35 x 14, 35 x 10","25 x 22, 25 x 14",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3/7/2023,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180 x 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3/8/2023,Rest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3/9/2023,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,3/10/2023,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3/11/2023,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,3/12/2023,Rest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3/13/2023,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,3/14/2023,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,3/15/2023,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,3/16/2023,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"135 x 18, 135 x 14","90 x 25, 90 x 21","22.5 x 10, 20 x 12",27.5 x 14,NaN,NaN,NaN,NaN,NaN,NaN
13,3/17/2023,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,3/18/2023,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"19, 16","70 x 13, 70 x 10, 70 x 8","40 x 18, 40 x 14",NaN,NaN
15,3/19/2023,Rest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,3/20/2023,1,"225 x 8, 235 x 6, 235 x 4","75 x 9, 75 x 8, 75 x 7","130 x 12, 130 x 11","90 x 18, 100 x 12, 100 x 13","25 x 18, 25 x 16, 25 x 15",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Initializing empty dataframes for data I'm interested in and creating dictionary in order to identify dfs by name from original dataset

benchPress = pd.DataFrame()
dumbBP = pd.DataFrame()
incDumbBP = pd.DataFrame()
squat = pd.DataFrame()
deadlift = pd.DataFrame()
overheadPress = pd.DataFrame()
pullUp = pd.DataFrame()
hammerCurl = pd.DataFrame()
skullcrusher = pd.DataFrame()

exerDict = {"Bench Press": benchPress, "Dumbbell Bench Press": dumbBP, "Incline Dumbbell Bench Press": incDumbBP, "Squat": squat, "Deadlift": deadlift, "Overhead Press": overheadPress, "Pull-up": pullUp, "Hammer Curl": hammerCurl, "Skullcrushers": skullcrusher}

In [6]:
# Iterating through all desired exercises I want to analyze starting with Bench Press, then searching through all of my past workout 
# programs starting with PPL in order to combine all data for each exercise from all programs into one dataframe for each exercise.  
# e.g. benchPress df will have all Bench Press data from all programs, squat df will have all Squat data from all programs, etc.
# Also dropping the irrelvant columns for unwanted exercises and dropping null rows


for exer_name, exer_df in exerDict.items():             # Iterating over each exercise I want data for
    for program in programs:                             # Iterating over each workout program
        iterDF = program[program.columns[program.columns.str.match('^Date|' + exer_name)]].copy()    
        # iterDF creates a dataframe storing all exercise data for the current program in the current exercise
        col = iterDF.columns
        iterDF.dropna(subset=col[1:], how='all', inplace=True)
        for col_name in col[1:]:
            iterDF[col[1]].fillna(iterDF[col_name], inplace=True)
        iterDF.dropna(axis=1, inplace=True)
        # dropping rows with all NA values for all the columns after date, combining data from the same exercise done on 
        # different days in the same program into the same column in the dataframe and dropping all the other columns
        exer_df = pd.concat([exer_df, iterDF], ignore_index=True)
        # concatenating current iterDF to DF in dictionary for current exercise.  e.g. concatenating bench press data from PPL 
        # program to benchPress df, then concatenating bench press data from pbv2 program to benchPress df, etc.  
        # Then, go through the same process for next exercise.
    exerDict[exer_name] = exer_df
    # After concatenating data for all programs of current exercise in loop, save that exercise's data into the dataframe.

In [7]:
# Saving dataframes in dictionary as their own dfs and putting them back into a list
benchPress = exerDict["Bench Press"]
dumbBP = exerDict["Dumbbell Bench Press"]
incDumbBP = exerDict["Incline Dumbbell Bench Press"]
squat = exerDict["Squat"]
deadlift = exerDict["Deadlift"]
overheadPress = exerDict["Overhead Press"]
pullUp = exerDict["Pull-up"]
hammerCurl = exerDict["Hammer Curl"]
skullcrusher = exerDict["Skullcrushers"]

exercises = [benchPress, dumbBP, incDumbBP, squat, deadlift, overheadPress, pullUp, hammerCurl, skullcrusher]
benchPress.head(20)

          Date                          Bench Press
0    11/9/2021                   145 x 10, 145 x 10
1   11/12/2021   160 x 5, 160 x 5, 160 x 5, 160 x 5
2   11/16/2021                     150 x 8, 155 x 8
3   11/19/2021   160 x 5, 165 x 5, 165 x 4, 160 x 5
4   11/23/2021                     150 x 9, 150 x 8
5   11/26/2021   160 x 5, 160 x 5, 160 x 5, 160 x 5
6   11/30/2021                     150 x 8, 150 x 8
7    12/3/2021   160 x 5, 160 x 5, 160 x 5, 160 x 5
8    12/7/2021                   145 x 10, 145 x 10
9   12/14/2021   165 x 4, 170 x 4, 170 x 4, 170 x 4
10   7/18/2022   160 x 4, 160 x 4, 155 x 6, 155 x 6
11   7/20/2022            175 x 1, 155 x 5, 140 x 9
12   7/26/2022            145 x 8, 145 x 7, 145 x 6
13    8/1/2022            175 x 2, 160 x 4, 160 x 3
14    8/3/2022           185 x 1, 155 x 6, 135 x 12
15    8/9/2022   155 x 8, 155 x 8, 155 x 7, 150 x 7
16   8/15/2022            160 x 5, 175 x 2, 175 x 2
17   8/17/2022           185 x 1, 155 x 6, 135 x 12
18   8/23/2022  155 x 8, 150 x 7, 150 x 6, 145 x 7
19   8/29/2022            155 x 8, 150 x 7, 150 x 6

In [8]:
# For each exercise df in exercises list, separating weight and reps into their own columns
for e in range(len(exercises)):
    exercises[e] = pd.concat([exercises[e], exercises[e].iloc[:, 1].str.split('x|,', expand=True).apply(lambda x: x.str.strip())], axis=1)
    # Dropping the original column
    exercises[e] = exercises[e].drop(exercises[e].columns[1], axis=1)
    new_col_names = []
    # Renaming each column
    for i in range(len(exercises[e].columns) - 1):
        # if odd number then weight column, if even then reps column
        column_type = 'Weight' if i % 2 == 0 else 'Reps'
        set_number = (i // 2) + 1
        # adding new column names to list
        new_col_names.extend(["Set {} {}".format(set_number, column_type)])
    # Renaming columns to values in list
    exercises[e].columns = ['Date'] + new_col_names

In [9]:
exercises[0].head(20)

,Date,Set 1 Weight,Set 1 Reps,Set 2 Weight,Set 2 Reps,Set 3 Weight,Set 3 Reps,Set 4 Weight,Set 4 Reps
0,11/9/2021,145,10,145,10,None,None,None,None
1,11/12/2021,160,5,160,5,160,5,160,5
2,11/16/2021,150,8,155,8,None,None,None,None
3,11/19/2021,160,5,165,5,165,4,160,5
4,11/23/2021,150,9,150,8,None,None,None,None
5,11/26/2021,160,5,160,5,160,5,160,5
6,11/30/2021,150,8,150,8,None,None,None,None
7,12/3/2021,160,5,160,5,160,5,160,5
8,12/7/2021,145,10,145,10,None,None,None,None
9,12/14/2021,165,4,170,4,170,4,170,4
10,7/18/2022,160,4,160,4,155,6,155,6
11,7/20/2022,175,1,155,5,140,9,None,None
12,7/26/2022,145,8,145,7,145,6,None,None
13,8/1/2022,175,2,160,4,160,3,None,None
14,8/3/2022,185,1,155,6,135,12,None,None
15,8/9/2022,155,8,155,8,155,7,150,7
16,8/15/2022,160,5,175,2,175,2,None,None
17,8/17/2022,185,1,155,6,135,12,None,None
18,8/23/2022,155,8,150,7,150,6,145,7
19,8/29/2022,155,8,150,7,150,6,None,None